spring.application.name=market-data
server.port=8083

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.discovery.enabled=true
eureka.client.fetch-registry=true

kraken.base-url=${KRAKEN_BASE_URL}
kraken.websocket=${KRAKEN_WEBSOCKET}
kraken.connect-timeout=5s
kraken.read-timeout=18s

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://market-data-db:5432/market_data
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true