
services:
  postgres:
    image: postgres:16
    container_name: trading-postgres
    environment:
      POSTGRES_DB: trading_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    networks:
      - trading-network

    restart: unless-stopped


  trading-app:
    build: ./trading-core
    container_name: trading-app
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/trading_os
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_ISSUER: ${JWT_ISSUER}
    depends_on:
      - postgres
    ports:
      - "8081:8081"

    networks:
      - trading-network

    restart: unless-stopped



  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

    networks:
        - trading-network

    restart: unless-stopped



  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      GATEWAY_PORT: 8080
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
        - trading-network



networks:
  trading-network:
    driver: bridge
