package com.hope.trading.market_intelligence.domain.trendcontext;

public enum TrendTimeframeAlignment {
    ALIGNED_UP, ALIGNED_DOWN, PULLBACK_WITHIN_UP_BIAS, PULLBACK_WITHIN_DOWN_BIAS,
    BIAS_TRANSITION, CONFLICTING, INSUFFICIENT_DIRECTION, INSUFFICIENT_BIAS,
    TRIGGER_CONTRADICTION, TRIGGER_UNAVAILABLE
}
