package com.hope.trading.broker_service.broker.api.controller;

import com.hope.trading.broker_service.broker.application.service.BrokerOperationServices.*;
import com.hope.trading.broker_service.broker.domain.model.BrokerModels.*;
import com.hope.trading.broker_service.security.BrokerPrincipal;
import com.hope.trading.broker_service.broker.domain.exception.BrokerExceptions.BrokerAuthorizationException;
import java.util.*;
import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.*;
import org.springframework.security.core.annotation.AuthenticationPrincipal;

public final class BrokerQueryControllers {private BrokerQueryControllers(){}
    @RestController @RequestMapping("/internal/v1/broker-accounts") public static final class AccountController {private final GetAccountService service;public AccountController(GetAccountService s){service=s;}@GetMapping("/{id}")public ResponseEntity<AccountSnapshot> get(@PathVariable UUID id){return ResponseEntity.ok(service.get(id));}}
    @RestController @RequestMapping("/internal/v1/broker-accounts") public static final class PositionController {private final GetPositionsService service;public PositionController(GetPositionsService s){service=s;}@GetMapping("/{id}/positions")public ResponseEntity<List<PositionSnapshot>> get(@PathVariable UUID id){return ResponseEntity.ok(service.get(id));}}
    @RestController @RequestMapping("/internal/v1/broker-accounts") public static final class OrderController {private final GetOrdersService service;public OrderController(GetOrdersService s){service=s;}@GetMapping("/{id}/orders")public ResponseEntity<List<OrderSnapshot>> get(@PathVariable UUID id){return ResponseEntity.ok(service.get(id));}}
    @RestController @RequestMapping("/internal/v1/broker-accounts") public static final class RiskSnapshotController {private final GetRiskSnapshotService service;public RiskSnapshotController(GetRiskSnapshotService s){service=s;}@GetMapping("/{id}/risk-snapshot")public ResponseEntity<RiskSnapshot> get(@PathVariable UUID id,@RequestParam java.time.Instant from,@RequestParam java.time.Instant to,@AuthenticationPrincipal BrokerPrincipal principal){if(principal==null||principal.userId()==null)throw new BrokerAuthorizationException("Delegated actor is required");return ResponseEntity.ok(service.get(principal.userId(),id,from,to));}}
    @RestController @RequestMapping("/internal/v1/broker-accounts") public static final class TechnicalCapabilitiesController {private final GetTechnicalCapabilitiesService service;public TechnicalCapabilitiesController(GetTechnicalCapabilitiesService s){service=s;}@GetMapping("/{id}/capabilities")public ResponseEntity<TechnicalCapabilities> get(@PathVariable UUID id,@RequestParam String instrument,@AuthenticationPrincipal BrokerPrincipal principal){if(principal==null||principal.userId()==null)throw new BrokerAuthorizationException("Delegated actor is required");return ResponseEntity.ok(service.get(principal.userId(),id,instrument));}}
    @RestController @RequestMapping("/internal/v1/broker-accounts") public static final class MarginPreviewController {private final PreviewMarginService service;public MarginPreviewController(PreviewMarginService s){service=s;}@PostMapping("/{id}/margin-preview")public ResponseEntity<MarginPreview> preview(@PathVariable UUID id,@RequestBody MarginPreviewRequest request,@AuthenticationPrincipal BrokerPrincipal principal){if(principal==null||principal.userId()==null)throw new BrokerAuthorizationException("Delegated actor is required");if(!id.equals(request.brokerAccountId()))throw new IllegalArgumentException("Broker account path does not match request");return ResponseEntity.ok(service.preview(request,principal.userId()));}}
}
