CREATE TABLE price_observations (
    observation_id UUID NOT NULL,
    market_id UUID NOT NULL,
    provider VARCHAR(255) NOT NULL,
    symbol VARCHAR(255) NOT NULL,
    base_asset VARCHAR(255) NOT NULL,
    quote_asset VARCHAR(255) NOT NULL,
    bid NUMERIC(38, 18),
    ask NUMERIC(38, 18),
    last_price NUMERIC(38, 18),
    effective_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    captured_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_price_observations PRIMARY KEY (observation_id),
    CONSTRAINT fk_price_observations_market FOREIGN KEY (market_id) REFERENCES markets (market_id)
);

CREATE INDEX ix_price_observation_market_time
    ON price_observations (market_id, effective_at DESC, captured_at DESC);
CREATE INDEX ix_price_observation_pair_time
    ON price_observations (base_asset, quote_asset, effective_at DESC, captured_at DESC);

CREATE TABLE valuation_snapshots (
    version BIGINT GENERATED BY DEFAULT AS IDENTITY,
    snapshot_id UUID NOT NULL,
    reporting_currency VARCHAR(255) NOT NULL,
    valuation_timestamp TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    captured_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    max_observation_age VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    CONSTRAINT pk_valuation_snapshots PRIMARY KEY (version),
    CONSTRAINT uk_valuation_snapshots_id UNIQUE (snapshot_id)
);

CREATE TABLE valuation_facts (
    fact_id UUID NOT NULL,
    snapshot_version BIGINT NOT NULL,
    request_type VARCHAR(32) NOT NULL,
    request_id VARCHAR(255) NOT NULL,
    market_id UUID,
    asset VARCHAR(255),
    price_use VARCHAR(32),
    source_observation_id UUID,
    source_market_id UUID,
    source_provider VARCHAR(255),
    source_symbol VARCHAR(255),
    source_price_type VARCHAR(32),
    source_price NUMERIC(38, 18),
    source_effective_at TIMESTAMP(6) WITH TIME ZONE,
    source_captured_at TIMESTAMP(6) WITH TIME ZONE,
    observation_age VARCHAR(64),
    valuation_value NUMERIC(38, 18),
    status VARCHAR(64) NOT NULL,
    CONSTRAINT pk_valuation_facts PRIMARY KEY (fact_id),
    CONSTRAINT fk_valuation_facts_snapshot FOREIGN KEY (snapshot_version) REFERENCES valuation_snapshots (version)
);

CREATE TABLE valuation_conversion_legs (
    leg_id UUID NOT NULL,
    fact_id UUID NOT NULL,
    from_currency VARCHAR(255) NOT NULL,
    to_currency VARCHAR(255) NOT NULL,
    rate NUMERIC(38, 18),
    source_observation_id UUID,
    source_market_id UUID,
    source_provider VARCHAR(255),
    source_symbol VARCHAR(255),
    source_price_type VARCHAR(32) NOT NULL,
    source_price NUMERIC(38, 18),
    source_effective_at TIMESTAMP(6) WITH TIME ZONE,
    source_captured_at TIMESTAMP(6) WITH TIME ZONE,
    observation_age VARCHAR(64),
    CONSTRAINT pk_valuation_conversion_legs PRIMARY KEY (leg_id),
    CONSTRAINT fk_conversion_legs_fact FOREIGN KEY (fact_id) REFERENCES valuation_facts (fact_id)
);
