spring.application.name=broker-service
server.port=8082

kraken.base-url=${KRAKEN_BASE_URL}
kraken.api-key=${KRAKEN_API_KEY}
kraken.api-secret=${KRAKEN_API_SECRET}
kraken.connect-timeout=5s
kraken.read-timeout=18s

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=5

logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.hope.trading=${LOG_LEVEL_APP:INFO}
logging.level.org.springframework=${LOG_LEVEL_SPRING:WARN}
