spring.application.name=broker-service
server.port=8082

kraken.base-url=${KRAKEN_BASE_URL}
kraken.api-key=${KRAKEN_API_KEY}
kraken.api-secret=${KRAKEN_API_SECRET}
kraken.connect-timeout=5s
kraken.read-timeout=18s

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.discovery.enabled=true
