create table broker_risk_snapshot (
    snapshot_version bigint generated by default as identity primary key,
    broker_account_id uuid not null,
    observed_at timestamp with time zone not null,
    completeness varchar(20) not null
);

create index ix_broker_risk_snapshot_account_version
    on broker_risk_snapshot (broker_account_id, snapshot_version desc);

create table broker_position_identity (
    position_id uuid primary key,
    broker_account_id uuid not null,
    provider varchar(40) not null,
    provider_position_reference varchar(200) not null,
    provider_reference_provenance varchar(80) not null,
    created_at timestamp with time zone not null,
    constraint uq_broker_position_provider_reference unique
        (broker_account_id, provider, provider_position_reference)
);

create index ix_broker_position_identity_account
    on broker_position_identity (broker_account_id);
