spring.application.name=eureka-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.hope.trading=${LOG_LEVEL_APP:INFO}
logging.level.org.springframework=${LOG_LEVEL_SPRING:WARN}
logging.level.com.netflix.eureka=${LOG_LEVEL_EUREKA:WARN}
