spring.application.name=trading-core
server.port=8081
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/trading_os
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.discovery.enabled=true
eureka.client.fetch-registry=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION}
security.jwt.issuer=${JWT_ISSUER}