logging.structured.format.console=logstash
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
security.service-jwt.enabled=true
security.service-jwt.secret=${TRADING_CORE_SERVICE_JWT_SECRET}
security.service-jwt.trusted.broker-service=${BROKER_SERVICE_SERVICE_JWT_SECRET}
security.service-jwt.trusted.market-intelligence=${MARKET_INTELLIGENCE_SERVICE_JWT_SECRET}
