sonar.projectKey=trading-os:trading-os-web
sonar.projectName=Trading OS - Web
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/trading-os-web/lcov.info
sonar.coverage.exclusions=src/main.ts
