package com.hope.trading.market_intelligence.domain.scope;

public enum MarketEligibilityReason {
    MARKET_NOT_FOUND,
    MARKET_NOT_TRADABLE,
    DATA_UNAVAILABLE,
    UNSUPPORTED_DATA,
    STALE_DATA,
    INSUFFICIENT_HISTORY,
    DATA_INTEGRITY_FAILURE,
    MARKET_FACT_EVALUATION_BUDGET_EXHAUSTED,
    BROKER_CAPABILITY_UNAVAILABLE,
    BROKER_MARKET_ORDER_UNSUPPORTED
}
